Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Datalayer;
using System.Net;

namespace MyEshop.Controllers
{
    public class ProductController : Controller
    {
        OnlineShopDBEntities db = new OnlineShopDBEntities();


        [ChildActionOnly]
        public ActionResult ShowProductGroups()
        {
            return PartialView(db.Product_Groups);   
        }

        public ActionResult LastProducts()
        {
            var products = db.Products.OrderByDescending(p => p.ProductCreateDate).Take(6);
            return PartialView(products);
        }

        public ActionResult MostSellingProducts()
        {
            var products = db.Products.OrderByDescending(p => p.ProductCreateDate).Take(6);
            return PartialView(products);
        }

        [Route("SingleProduct/{id}")]
        public ActionResult SingleProduct(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var product = db.Products.Find(id);
            if(product == null)
            {
                return HttpNotFound();  
            }
            var featureIds = product.ProductFeatures.GroupBy(f => f.FeatureId).Select(f => f.Key).ToList();
            List<ProductFeatureViewModel> features = new List<ProductFeatureViewModel>();
            foreach(var featureId in featureIds)
            {
                var productFeature = new ProductFeatureViewModel()
                {
                    FeatureTitle = db.Features.Single(f => f.FeatureId == featureId).FeatureTitle,
                    Values = product.ProductFeatures.Where(f => f.FeatureId == featureId).Select(f => f.Value).ToList()
                };

                features.Add(productFeature);
            }
            ViewBag.ProductFeatures = features;
            return View(product);
        }


        [ChildActionOnly]
        public ActionResult ShowComments(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (! db.Products.Any(p => p.ProductID == id))
            {
                return HttpNotFound();
            }
            var comments = db.Product_Comments.Where(p => p.ProductID == id);
            return PartialView(comments);
        }

        public ActionResult CreateComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!db.Products.Any(p => p.ProductID == id))
            {
                return HttpNotFound();
            }
            return PartialView(new Product_Comments() { ProductID = id.Value});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateComment([Bind(Include = "CommentId, ProductID, Name, Email, Website, Comment, ParentId")] Product_Comments productComment)
        {
            if (ModelState.IsValid)
            {
                productComment.CreateDate = DateTime.Now;
                db.Product_Comments.Add(productComment);
                db.SaveChanges();
                return PartialView("ShowComments", db.Product_Comments.Where(p => p.ProductID == productComment.ProductID));
            }
            return PartialView(productComment);
        }

        [Route("Archieve")]
        public ActionResult Archieve(int pageId=1, string title="", int minPrice=0, int maxPrice=0 , List<int> selectedGroups = null)
        {
            List<Product> products = new List<Product>();
            if(selectedGroups != null)
            {
               foreach(var groupId in selectedGroups)
                {
                    products.AddRange(db.Product_SelectedGroups.Where(g => g.GroupId == groupId).Select(g=> g.Product).ToList());
                }
               products = products.Distinct().ToList();
            }
            else
            {
                products = db.Products.ToList();
            }
            if(! String.IsNullOrWhiteSpace(title))
            {
                title = title.Trim().ToLower();
                products = products.Where(p => p.ProductTitle.ToLower().Contains(title)).ToList();
            }
            if(minPrice > 0)
            {
                products = products.Where(p => p.ProductPrice >= minPrice).ToList();
            }
            if (maxPrice > 0)
            {
                products = products.Where(p => p.ProductPrice <= maxPrice).ToList();
            }
            ViewBag.selectedGroupsList = selectedGroups;
            ViewBag.PageId = pageId;
            ViewBag.groups = db.Product_Groups.ToList();

            //Paging
            int take = 3;
            int skip = (pageId - 1) * take;
            // ViewBag.PagesCount = (int) Math.Ceiling(products.Count / take);
            double pegeCount = 1.0 * products.Count / take;
            ViewBag.PagesCount = Math.Ceiling(pegeCount);
            return View(products.OrderByDescending(p => p.ProductCreateDate).Skip(skip).Take(take));
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ShopController.cs
using Datalayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MyEshop.Controllers
{
    public class ShopController : Controller
    {
        OnlineShopDBEntities db = new OnlineShopDBEntities();
        // GET: Shop
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Orders()
        {
            return PartialView(GetOrdersList());
        }

        public ActionResult ChangeCount(int id, int count)
        {
            List<ShopCartItem> cartItems = Session["ShopCart"] as List<ShopCartItem>;
            if (cartItems.Any(p => p.ProductID == id))
            {
                int index = cartItems.FindIndex(p => p.ProductID == id);
                if (count == 0)
                {
                    cartItems.RemoveAt(index);
                }
                else
                {
                    cartItems[index].Count = count;
                }
            }
            Session["ShopCart"] = cartItems;
            return PartialView("Orders", GetOrdersList());
        }

        public int ShopItemsCount()
        {
            List<ShopCartItem> cartItems = new List<ShopCartItem>();
            if (Session["ShopCart"] != null)
            {
                cartItems = Session["ShopCart"] as List<ShopCartItem>;
            }
            return cartItems.Sum(p => p.Count);
        }

        public int AddToCart(int? id)
        {
            List<ShopCartItem> cartItems = new List<ShopCartItem>();
            if (Session["ShopCart"] != null)
            {
                cartItems = Session["ShopCart"] as List<ShopCartItem>;
            }
            if (id != null && db.Products.Any(p => p.ProductID == id))
            {
                if (cartItems.Any(p => p.ProductID == id))
                {
                    int index = cartItems.FindIndex(p => p.ProductID == id);
                    cartItems[index].Count += 1;
                }
                else
                {
                    cartItems.Add(new ShopCartItem()
                    {
                        ProductID = id.Value,
                        Count = 1
                    });
                }
            }
            Session["ShopCart"] = cartItems;
            return ShopItemsCount();
        }

        public ActionResult ShowBasketSide()
        {
            List<ShopCartItemViewModel> cartItems = new List<ShopCartItemViewModel>();
            if (Session["ShopCart"] != null)
            {
                List<ShopCartItem> itemsList = Session["ShopCart"] as List<ShopCartItem>;
                foreach (var item in itemsList)
                {
                    var product = db.Products.Where(p => p.ProductID == item.ProductID).Select(p => new { p.ProductImageName, p.ProductTitle }).Single();
                    cartItems.Add(new ShopCartItemViewModel()
                    {
                        ProductID = item.ProductID,
                        Count = item.Count,
                        Title = product.ProductTitle,
                        ImageName = product.ProductImageName

                    });
                }
            }
            return PartialView(cartItems);
        }

        [Authorize]
        public ActionResult Payment()
        {
            int userId = db.Users.Single(u => u.Username == User.Identity.Name).UserId;
            var order = new Order()
            {
                UserId = userId,
                Date = DateTime.Now,
                IsFinally = false
            };
            db.Orders.Add(order);

            int amount = 0;
            var cartItems = GetOrdersList();
            foreach (var cartItem in cartItems)
            {
                db.OrderDetails.Add(new OrderDetail()
                {
                    ProductId = cartItem.ProductID,
                    Count = cartItem.Count,
                    OrderId = order.OrderId,
                    Price = cartItem.Price
                });
                amount += cartItem.Price * cartItem.Count;
            }
            db.SaveChanges();

            // Zarinpal Payment
            System.Net.ServicePointManager.Expect100Continue = false;
            Zarinpal.PaymentGatewayImplementationServicePortTypeClient zp = new Zarinpal.PaymentGatewayImplementationServicePortTypeClient();
            string Authority;

            int Status = zp.PaymentRequest("YOUR-ZARINPAL-MERCHANT-CODE", amount, "My Personal Description", "you@yoursite.com", "09123456789", "https://localhost:44338/Shop/Verify/" + order.OrderId, out Authority);

            if (Status == 100)
            {
                Response.Redirect("https://sandbox.zarinpal.com/pg/StartPay/" + Authority);
            }
            else
            {
                ViewBag.Error = Status;
                Response.Write("error: " + Status);
            }

            return View();
        }

        public ActionResult Verify(int id)
        {
            if (Request.QueryString["Status"] != "" && Request.QueryString["Status"] != null && Request.QueryString["Authority"] != "" && Request.QueryString["Authority"] != null)
            {
                if (Request.QueryString["Status"].ToString().Equals("OK"))
                {
                    var order = db.Orders.Find(id);
                    int Amount = order.OrderDetails.Sum(o => o.Count*o.Price);
                    long RefID;
                    System.Net.ServicePointManager.Expect100Continue = false;
                    Zarinpal.PaymentGatewayImplementationServicePortTypeClient zp = new Zarinpal.PaymentGatewayImplementationServicePortTypeClient();

                    int Status = zp.PaymentVerification("YOUR-ZARINPAL-MERCHANT-CODE", Request.QueryString["Authority"].ToString(), Amount, out RefID);

                    if (Status == 100)
                    {
                        order.IsFinally = true;
                        db.SaveChanges();
                        Session["ShopCart"] = null;
                        ViewBag.RefID = RefID;
                        ViewBag.Success = true;
                    }
                    else
                    {
                        ViewBag.Status = Status;
                        ViewBag.Success = false;
                    }

                }
                else
                {
                    ViewBag.Authority = Request.QueryString["Authority"].ToString();
                    ViewBag.Status = Request.QueryString["Status"].ToString();
                    ViewBag.Error = true;
                }
            }
            else
            {
                ViewBag.InvalidInput = true;
            }
            return View();
        }

        private List<OrderFactorViewModel> GetOrdersList()
        {
            List<OrderFactorViewModel> ordersList = new List<OrderFactorViewModel>();
            if (Session["ShopCart"] != null)
            {
                List<ShopCartItem> itemsList = Session["ShopCart"] as List<ShopCartItem>;
                foreach (var item in itemsList)
                {
                    var product = db.Products.Where(p => p.ProductID == item.ProductID).Select(p => new { p.ProductImageName, p.ProductTitle, p.ProductPrice }).Single();
                    ordersList.Add(new OrderFactorViewModel()
                    {
                        ProductID = item.ProductID,
                        Count = item.Count,
                        Title = product.ProductTitle,
                        ImageName = product.ProductImageName,
                        Price = product.ProductPrice,
                        Sum = item.Count * product.ProductPrice

                    });
                }
            }
            return ordersList;
        }
    }
}

Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html class="no-js" dir="rtl" lang="fa-IR">
<head>
    <meta charset="UTF-8">
    <title>@ViewBag.Title - EShop </title>
    <base href="">
    <meta name="googlebot" content="index,follow">
    <meta name="robots" content="noodp,noydir">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/Content/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/bootstrap-rtl.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/carousel.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/Content/css/style.css">
    <script src="/Content/js/jquery-v1.11.3.js"></script>
</head>
<body>
    <script src="/Content/js/modernizr.js"></script>
    <div class="top-nav">
        <div class="container">
            <div class="col-md-6 col-sm-7 col-xs-7 right-nav">
                <!-- Clientarea and Basket -->
                <div class="clientarea">
                    <ul>
                        @Html.Partial("_LoggedInUser")
                        <li><a href="/Shop"><i class="fa fa-shopping-bag"></i> سبد خرید <span id="shopItemsCount"></span></a></li>
                    </ul>
                </div>
                <!-- End Clientarea and Basket -->
            </div>
            <div class="col-md-6 col-sm-5 col-xs-5 left-nav">
                <!-- Social -->
                <div class="socials">
                    <ul>
                        <li><a href="" class="social-icon" data-balloon=" اینستاگرام " data-balloon-pos="down"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="" class="social-icon" data-balloon=" لینکداین " data-balloon-pos="down"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="" class="social-icon" data-balloon=" فیس بوک " data-balloon-pos="down"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="" class="social-icon" data-balloon=" تلگرام " data-balloon-pos="down"><i class="fa fa-paper-plane"></i></a></li>
                        <li><a href="" class="social-icon" data-balloon=" توئیتر " data-balloon-pos="down"><i class="fa fa-twitter"></i></a></li>
                    </ul>
                </div>
                <!-- End Social -->
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- site Header -->
    <header class="header-site">
        <div class="container">
            <div class="col-md-7 col-sm-7 logo-layer">
                <a href="" class="logo"><img src="/Content/img/logo.png"></a>
                <h1>فروشگاه <span>آنلایــــــن</span> </h1>
                <h2>آموزشگاه برنامه نویســـان</h2>
            </div>
            <div class="col-md-5 col-sm-5 left-header-site">
                <h5> پشتیبانــــی 24 ساعتـــــه </h5>
                <h3> 09124140939 <i class="icon-phone"></i></h3>
            </div>
            <div class="clearfix"></div>
        </div>
    </header>
    <!-- End site Header -->
    <!-- Mega Menu -->
    <nav class="mega-menu">
        <div class="container">
            <span class="responsive-list"><i class="fa fa-th-list"></i></span>
            <ul>
                <li><a href="/">صفحه اصلی </a></li>
                <li><a href="/Archieve"> آرشیو محصولات </a></li>

            </ul>

            <!-- Search -->
            <div class="form-search">
                <span><i class="fa fa-search"></i></span>
                <form action="/Search" method="get">
                    <input type="text" name="q" placeholder=" جستجو کنید ..." class="border-radius">
                    <button type="submit" class="border-radius"> بگرد </button>
                </form>
            </div>
            <!-- End Search -->

        </div>
    </nav>
    <!-- End Mega Menu -->
    <!-- slider -->
    @RenderSection("slider", false)
    <!-- End slider -->

    <div class="container margin-top-25">
        <aside class="col-md-3 col-sm-4 right-side-content">
            @RenderSection("Filters" , false)
            <!-- Basket -->
            <div id="showBasketSide">
            @Html.Action("ShowBasketSide","Shop", new {area =""})
             </div>
            <!-- End Basket -->
            <!-- compare -->
            <section class="border-radius compare-side">
                <header><h3> لیست مقایسه </h3></header>
                <article>
                    <ul>
                        <li>
                            <i class="delete-compare">X</i>
                            <a href="">محصول شماره یک </a>
                        </li>
                        <li>
                            <i class="delete-compare">X</i>
                            <a href="">محصول شماره یک </a>
                        </li>
                        <li>
                            <i class="delete-compare">X</i>
                            <a href="">محصول شماره یک </a>
                        </li>
                    </ul>
                    <a href="" class="show-compare-list border-radius">مشاهده لیست مقایسه</a>
                </article>
            </section>
            <!-- End compare -->
            <!-- Category -->
            @Html.Action("ShowProductGroups", "Product", new { area = "" })
            <!-- End Category -->
            <!-- Category -->
            <!-- End Category -->
        </aside>
        <div class="col-md-9 col-sm-8 left-side-content">

            @RenderBody()

        </div>
        <div class="clearfix"></div>
    </div>

    <footer>
        <div class="top-footer">
            <div class="container">
                <section class="col-lg-4 col-md-4 permalink-section">
                    <header><h3> دسترسی سریع </h3></header>
                    <article>
                        <ul>
                            <li><a href=""> صفحه اصلی </a></li>
                            <li><a href=""> ورود به سایت </a></li>
                            <li><a href=""> عضویت در سایت </a></li>
                            <li><a href=""> قوانین سایت </a></li>
                            <li><a href=""> راهنمای خرید </a></li>
                            <li><a href=""> سوالات متداول </a></li>
                            <li><a href=""> ورود به سایت </a></li>
                            <li><a href=""> عضویت در سایت </a></li>
                        </ul>
                    </article>
                </section>
                <section class="col-lg-4 col-md-4 permalink-section">
                    <header><h3> لینک های مفید </h3></header>
                    <article>
                        <ul>
                            <li><a href="">پرسش های متداول پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول پرسش های متداول </a></li>
                            <li><a href="">پرسش های متداول </a></li>
                        </ul>
                    </article>
                </section>
                <section class="col-lg-4 col-md-4 contact-section">
                    <header><h3> تماس با ما </h3></header>
                    <article>
                        <p><i class="fa fa-map-o"></i> نشانی :  تهران ، خیابان شریعتی ، ابتدای خیابان ملک ، کوچه ایرانیاد ، پلاک 1 ، آموزشگاه برنامه نویسان</p>
                        <p><i class="fa fa-volume-control-phone"></i> 021-88454816 </p>
                        <p><i class="fa fa-envelope"></i> info@barnamenevisan.com</p>
                        <p><i class="fa fa-fax"></i> 021-88454816 </p>
                    </article>
                </section>
            </div>
        </div>

        <div class="bottom-footer">
            <div class="container">
                <div class="col-lg-8 col-md-8 col-sm-6">
                    <ul>
                        <li><a href=""> خانه </a></li>
                        <li><a href="">قوانین سایت </a></li>
                        <li><a href=""> درباره ما </a></li>
                        <li><a href=""> تماس با ما </a></li>
                    </ul>
                    <p>Ⓒ تمام حقوق مادی ومعنوی این سایت متعلق به " <a href=""> آموزشگاه برنامه نویسان </a> " می باشد.</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <div class="social-layer">
                        <a href="" class="border-radius"><i class="fa fa-facebook"></i></a>
                        <a href="" class="border-radius"><i class="fa fa-linkedin"></i></a>
                        <a href="" class="border-radius"><i class="fa fa-twitter"></i></a>
                        <a href="" class="border-radius"><i class="fa fa-google-plus"></i></a>
                        <a href="" class="border-radius"><i class="fa fa-paper-plane"></i></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </footer>

    <script src="/Content/js/bootstrap.min.js"></script>
    <script src="/Content/js/owl.carousel.js"></script>
    <script src="/Content/js/script.js"></script>
    <script src="~/Content/js/jquery.validate.min.js"></script>
    <script src="~/Content/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/js/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("Scripts", false)
    <script>

        $(function () {
            ShopItemsCount();
        });

        function ShopItemsCount() {
            $.get("/Shop/ShopItemsCount", function (res) {
                $("#shopItemsCount").html(res);
            });
        }

        function AddToCart(id) {
            $.get("/Shop/AddToCart/" + id, function (res) {
                $("#shopItemsCount").html(res);
                UpdateBasketSide();
            });
        }

        function UpdateBasketSide() {
            $("#showBasketSide").load("/Shop/ShowBasketSide");
        }

        function ChangeCount(id, count) {
            $.ajax({
                url: "/Shop/ChangeCount/" + id,
                type: "Get",
                data: {count:count}
            }).done(function (res) {
                $("#ordersFactor").html(res);
                ShopItemsCount();
                UpdateBasketSide();
            });
        }

    </script>
</body>
</html>

Views/Shared/_LoggedInUser.cshtml
@if (User.Identity.IsAuthenticated)
{
    <li><a href="/UserPanel/Home/Index"><i class="fa fa-user"></i> <label>@User.Identity.Name</label> </a></li>

    if (User.IsInRole("admin"))
    {
        <li><a href="/Admin/Home/Index"><i class="fa fa-tasks"></i> <label>پنل مدیریت</label> </a></li>
    }
    <li class="text-danger"><a href="/Account/Signout"><i class="fa fa-sign-out"></i> <label>خروج</label> </a></li>

}
else
{
    <li><a href="/Register"><i class="fa fa-user-plus"></i> <label>عضویت</label> </a></li>
    <li><a href="/Login"><i class="fa fa-user"></i> <label>ورود به سایت</label> </a></li>
}

Views/Shared/_ProductBox.cshtml
@model Datalayer.Product

<div class="col-md-4 col-sm-6">
    <div class="border-radius">

        <div class="text-center">
            <a href="/SingleProduct/@Model.ProductID"> 
                <img class="img-box" src="~/Images/ProductImages/Thumb/@Model.ProductImageName" style="height:120px;">
            </a>
        </div>

        <h2 class="text-center">
            <a href="/SingleProduct/@Model.ProductID">
                @Model.ProductTitle
            </a>
        </h2>

        <h6>افزودن به لیست مقایسه <input type="checkbox" id="compare_@Model.ProductID" onchange="CheckCompareStatus(@Model.ProductID)"></h6>
        <span class="col-md-9 col-sm-9 col-xs-9 price-layer">
            <label>@Model.ProductPrice.ToString("#,0")  تومان</label>
        </span>
        <a onclick="AddToCart(@Model.ProductID)" class="col-md-2 col-sm-2 col-xs-2 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 buy-button border-radius">
            <label><i class="fa fa-shopping-basket"></i></label>
        </a>
    </div>
</div>