Areas/Admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datalayer;
using System.IO;

namespace MyEshop.Areas.Admin.Controllers
{
    public class SlidersController : Controller
    {
        private OnlineShopDBEntities db = new OnlineShopDBEntities();

        // GET: Admin/Sliders
        public ActionResult Index()
        {
            return View(db.Sliders.ToList());
        }

        // GET: Admin/Sliders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Sliders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SliderId,Title,ImageName,StartDate,EndDate,IsActive,Url")] Slider slider , HttpPostedFileBase imgUp)
        {
            if (ModelState.IsValid)
            {
                if(imgUp == null || !imgUp.IsImage())
                {
                    ModelState.AddModelError("ImageName", "لطفا یک تصویر انتخاب کنید");
                    return View(slider);
                }

                slider.ImageName = Guid.NewGuid().ToString() + Path.GetExtension(imgUp.FileName);
                imgUp.SaveAs(Server.MapPath("/Images/SliderImages/" + slider.ImageName));
                ImageResizer img = new ImageResizer();
                img.Resize(Server.MapPath("/Images/SliderImages/" + slider.ImageName), Server.MapPath("/Images/SliderImages/Thumb/" + slider.ImageName));

                db.Sliders.Add(slider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SliderId,Title,ImageName,StartDate,EndDate,IsActive,Url")] Slider slider, HttpPostedFileBase imgUp)
        {
            if (ModelState.IsValid)
            {
                if (imgUp != null && imgUp.IsImage())
                {
                    System.IO.File.Delete(Server.MapPath("/Images/SliderImages/" + slider.ImageName));
                    System.IO.File.Delete(Server.MapPath("/Images/SliderImages/Thumb/" + slider.ImageName));

                    slider.ImageName = Guid.NewGuid().ToString() + Path.GetExtension(imgUp.FileName);
                    imgUp.SaveAs(Server.MapPath("/Images/SliderImages/" + slider.ImageName));
                    ImageResizer img = new ImageResizer();
                    img.Resize(Server.MapPath("/Images/SliderImages/" + slider.ImageName), Server.MapPath("/Images/SliderImages/Thumb/" + slider.ImageName));
                }
                    db.Entry(slider).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }
            return View(slider);
        }

        // GET: Admin/Sliders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slider slider = db.Sliders.Find(id);
            if (slider == null)
            {
                return HttpNotFound();
            }
            return View(slider);
        }

        // POST: Admin/Sliders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slider slider = db.Sliders.Find(id);
            System.IO.File.Delete(Server.MapPath("/Images/SliderImages/" + slider.ImageName));
            System.IO.File.Delete(Server.MapPath("/Images/SliderImages/Thumb/" + slider.ImageName));
            db.Sliders.Remove(slider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Sliders/Create.cshtml
@model Datalayer.Slider

@{
    ViewBag.Title = "Create";
}

<h4>افزودن اسلایدر جدید</h4>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"> اسلایدر</h3>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Create", "Sliders", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group mb-3">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <img id="imgPreview" class="thumbnail center-block max-w-100" src="~/Images/ProductImages/default_image.png" />
                                <input type="file" name="imgUp" id="imgUp" accept="image/*" />
                                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { Value = DateTime.Now.ToString("yyyy/MM/dd") } })
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { Value = DateTime.Now.ToString("yyyy/MM/dd") } })
                                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group mb-3">
                            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.IsActive)
                                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="ثبت" class="btn btn-success w-100" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
        <div>
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    </div>
</div>




@section Scripts{
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/Content/js/kendo.all.min.js"></script>
    <script>

        $(document).ready(function () {

            // create DatePicker from input HTML element
            $("#StartDate").kendoDatePicker();
            $("#EndDate").kendoDatePicker();
        });

    </script>
    <script type="text/javascript">

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            } else {
                $('#preview').attr('src', '');
            }
        }

        $("#imgUp").change(function () {
            readURL(this);
        });
    </script>
}

Areas/Admin/Views/Sliders/Delete.cshtml
@model Datalayer.Slider

@{
    ViewBag.Title = "Delete";
}

<h4>حذف</h4>

<p>آیا از حذف این آیتم مطمئن هستید؟</p>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"> اسلایدر</h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.ImageName)
                    </dt>

                    <dd>
                        <img src="~/Images/SliderImages/Thumb/@Model.ImageName" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.StartDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.StartDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.EndDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.EndDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Url)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Url)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                </dl>
            </div>
        </div>
    </div>
</div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-danger" /> |
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    }

Areas/Admin/Views/Sliders/Details.cshtml
@model Datalayer.Slider

@{
    ViewBag.Title = "Details";
}

<h4>مشاهده جزییات</h4>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"> اسلایدر</h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.ImageName)
                    </dt>

                    <dd>
                        <img src="~/Images/SliderImages/Thumb/@Model.ImageName" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.StartDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.StartDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.EndDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.EndDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Url)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Url)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                </dl>
            </div>
        </div>
     </div>
</div>

                <p>
                    @Html.ActionLink("ویرایش", "Edit", new { id = Model.SliderId }, new { @class = "btn btn-sm btn-warning" }) |
                    @Html.ActionLink("بازگشت به لیست", "Index")
                </p>

Areas/Admin/Views/Sliders/Edit.cshtml
@model Datalayer.Slider

@{
    ViewBag.Title = "Edit";
}

<h4>ویرایش</h4>

<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"> اسلایدر</h3>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Edit", "Sliders", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.SliderId)
                    @Html.HiddenFor(model => model.ImageName)

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img id="imgPreview" class="thumbnail center-block max-w-100" src="~/Images/SliderImages/@Model.ImageName" />
                            <input type="file" name="imgUp" id="imgUp" accept="image/*" />
                            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { Value = Model.StartDate.ToString("yyyy/MM/dd") } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { Value = Model.EndDate.ToString("yyyy/MM/dd") } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="ثبت" class="btn btn-success w-100" />
                        </div>
                    </div>
                </div>
                }

            </div>
        </div>
        <div>
            @Html.ActionLink("بازگشت به لیست", "Index")
        </div>
    </div>
</div>




@section Scripts{
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2013.2.918/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="~/Content/js/kendo.all.min.js"></script>
    <script>

        $(document).ready(function () {

            // create DatePicker from input HTML element
            $("#StartDate").kendoDatePicker();
            $("#EndDate").kendoDatePicker();
        });

    </script>
    <script type="text/javascript">

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgPreview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            } else {
                $('#preview').attr('src', '');
            }
        }

        $("#imgUp").change(function () {
            readURL(this);
        });
    </script>
}

Areas/Admin/Views/Sliders/Index.cshtml
@model IEnumerable<Datalayer.Slider>

@{
    ViewBag.Title = "Index";
}

<h4>لیست</h4>

<p>
    @Html.ActionLink("افزودن آیتم جدید", "Create", null , new {@class="btn btn-success"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="~/Images/SliderImages/Thumb/@item.ImageName" alt="@item.Title"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("ویرایش", "Edit", new { id = item.SliderId }, new { @class = "btn btn-sm btn-warning" }) |
            @Html.ActionLink("مشاهده", "Details", new { id = item.SliderId }, new { @class = "btn btn-sm btn-primary" }) |
            @Html.ActionLink("حذف", "Delete", new { id = item.SliderId }, new { @class = "btn btn-sm btn-danger" })
        </td>
    </tr>
}

</table>