Areas/Admin/Controllers/FeaturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Datalayer;

namespace MyEshop.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class FeaturesController : Controller
    {
        private OnlineShopDBEntities db = new OnlineShopDBEntities();

        // GET: Admin/Features
        public ActionResult Index()
        {
            return View(db.Features.ToList());
        }

        public ActionResult ListFeatures()
        {
            var features = db.Features.ToList();
            return PartialView(features);
        }

        // GET: Admin/Features/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Admin/Features/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FeatureId,FeatureTitle")] Feature feature)
        {
            if (ModelState.IsValid)
            {
                db.Features.Add(feature);
                db.SaveChanges();
                return PartialView("ListFeatures" , db.Features);
            }

            return View(feature);
        }

        // GET: Admin/Features/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feature feature = db.Features.Find(id);
            if (feature == null)
            {
                return HttpNotFound();
            }
            return PartialView(feature);
        }

        // POST: Admin/Features/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FeatureId,FeatureTitle")] Feature feature)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feature).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("ListFeatures", db.Features);
            }
            return View(feature);
        }

        // GET: Admin/Features/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feature feature = db.Features.Find(id);
            if (feature == null)
            {
                return HttpNotFound();
            }
            return PartialView(feature);
        }

        // POST: Admin/Features/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Feature feature = db.Features.Find(id);
            db.Features.Remove(feature);
            db.SaveChanges();
            return PartialView("ListFeatures", db.Features);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Features/Create.cshtml
@model Datalayer.Feature

@{
    ViewBag.Title = "Create";
}


@using (Ajax.BeginForm("Create" , "Features" , FormMethod.Post , ajaxOptions: new AjaxOptions
{
    OnSuccess = "successAjax",
    UpdateTargetId = "featuresList"
})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group mb-3">
            @Html.LabelFor(model => model.FeatureTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FeatureTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FeatureTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-success w-100" />
            </div>
        </div>
    </div>
}

Areas/Admin/Views/Features/Delete.cshtml
@model Datalayer.Feature

@{
    ViewBag.Title = "Delete";
}

<p>آیا از حذف این آیتم مطمئن هستید؟</p>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FeatureTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeatureTitle)
        </dd>

    </dl>

    @using (Ajax.BeginForm("Delete", "Features", FormMethod.Post, ajaxOptions: new AjaxOptions
    {
        OnSuccess = "successAjax",
        UpdateTargetId = "featuresList"
    }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-danger" />
        </div>
    }
</div>

Areas/Admin/Views/Features/Edit.cshtml
@model Datalayer.Feature

@{
    ViewBag.Title = "Edit";
}


@using (Ajax.BeginForm("Edit", "Features", FormMethod.Post, ajaxOptions: new AjaxOptions
{
    OnSuccess = "successAjax",
    UpdateTargetId = "featuresList"
}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FeatureId)

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.FeatureTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FeatureTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FeatureTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-success w-100" />
            </div>
        </div>
    </div>
}

Areas/Admin/Views/Features/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2> لیست ویژگی ها</h2>

<p>
    <a onclick="Create()" class="btn btn-success">افزودن ویژگی جدید </a>
</p>
<div id="featuresList">
    @Html.Action("ListFeatures")
</div>
<!-- Modal -->
<div class="modal fade" id="featuresModal" tabindex="-1" role="dialog" aria-labelledby="groupsModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="featuresModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="featuresModalBody">
                <div id="errors"></div>
            </div>
        </div>
    </div>
</div>

@section scripts
    {
    <script>


        function Create() {
            $.get("/Admin/Features/Create", function (result) {
                $("#featuresModalLabel").html("افزودن ویژگی جدید");
                $("#featuresModalBody").html(result);
                $("#featuresModal").modal();
            });
        }

        function successAjax() {
            $("#featuresModal").modal('hide');
        }

        function Edit(id) {
            $.get("/Admin/Features/Edit/" + id, function (result) {
                $("#featuresModalLabel").html("ویرایش ویژگی ");
                $("#featuresModalBody").html(result);
                $("#featuresModal").modal();
            });
        }


        function Delete(id) {
            $.get("/Admin/Features/Delete/" + id, function (result) {
                $("#featuresModalLabel").html("حذف ویژگی ");
                $("#featuresModalBody").html(result);
                $("#featuresModal").modal();
            });
        }


    </script>
}

Areas/Admin/Views/Features/ListFeatures.cshtml
@model IEnumerable<Datalayer.Feature>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FeatureTitle)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FeatureTitle)
            </td>
            <td>
                <a class="tbtn btn-sm btn-warning" onclick="Edit(@item.FeatureId)"><i class="fa fa-edit"></i> </a>
                <a class="tbtn btn-sm btn-danger" onclick="Delete(@item.FeatureId)"><i class="fa fa-trash"></i> </a>
            </td>
        </tr>
    }
</table>